apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-todo
  template:
    metadata:
      labels:
        app: react-todo
    spec:
      containers:
      - name: react-todo
        image: priyam14/react-todolist:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
